options:
  formatter: stylish
files:
  include: 'src/scss/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude: ['media-query-under']

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 2
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 1
  no-color-literals: 1
  no-combinators: 0
  no-css-comments: 1
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-whitespace: 2
  no-trailing-zero: 0
  no-transition-all: 1
  no-universal-selectors: 0
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 0

  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1

  # Name Formats
  class-name-format:
      - 2
      -
        convention: strictbem
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 2
  brace-style: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    -
      size: 4
  leading-zero:
    - 2
    - include: true
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth:
      - 1
      - max-depth: 3
  property-sort-order:
    - 1
    -
      order: smacss
      ignore-custom-properties: true
  pseudo-element: 1
  quotes:
    - 2
    - style: single
  shorthand-values: 1
  url-quotes: 1
  variable-for-property:
    - 2
    -
      properties:
        - color
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 2
  final-newline: 2